// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN6uAkXVceoRBrCYKqhQG964fC0CrlA90',
    appId: '1:925752366644:web:cae7577b2d8026029d9c61',
    messagingSenderId: '925752366644',
    projectId: 'project-collaboration-ap-eb2e5',
    authDomain: 'project-collaboration-ap-eb2e5.firebaseapp.com',
    storageBucket: 'project-collaboration-ap-eb2e5.firebasestorage.app',
    measurementId: 'G-N6FRLKJEER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgzSyNK1Gj6OZAaNHcc0kuP3Ki5X5UyCs',
    appId: '1:925752366644:android:3ec53b5a6d234f0b9d9c61',
    messagingSenderId: '925752366644',
    projectId: 'project-collaboration-ap-eb2e5',
    storageBucket: 'project-collaboration-ap-eb2e5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC11ETBVZ-d2AWwW6OIGxuUJC0DVtteNrM',
    appId: '1:925752366644:ios:3155b81c667485039d9c61',
    messagingSenderId: '925752366644',
    projectId: 'project-collaboration-ap-eb2e5',
    storageBucket: 'project-collaboration-ap-eb2e5.firebasestorage.app',
    androidClientId: '925752366644-qhhsloppc68ab8bde7sbdbn7queg09jn.apps.googleusercontent.com',
    iosClientId: '925752366644-mjskahndlp3ui9lrgjctmo0lpq21obap.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectCollaborationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC11ETBVZ-d2AWwW6OIGxuUJC0DVtteNrM',
    appId: '1:925752366644:ios:3155b81c667485039d9c61',
    messagingSenderId: '925752366644',
    projectId: 'project-collaboration-ap-eb2e5',
    storageBucket: 'project-collaboration-ap-eb2e5.firebasestorage.app',
    androidClientId: '925752366644-qhhsloppc68ab8bde7sbdbn7queg09jn.apps.googleusercontent.com',
    iosClientId: '925752366644-mjskahndlp3ui9lrgjctmo0lpq21obap.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectCollaborationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN6uAkXVceoRBrCYKqhQG964fC0CrlA90',
    appId: '1:925752366644:web:66f44cb900f2b4cb9d9c61',
    messagingSenderId: '925752366644',
    projectId: 'project-collaboration-ap-eb2e5',
    authDomain: 'project-collaboration-ap-eb2e5.firebaseapp.com',
    storageBucket: 'project-collaboration-ap-eb2e5.firebasestorage.app',
    measurementId: 'G-XT37YM6X56',
  );

}